### ISSUE TITLE
Update Home page

### ISSUE THREAD

**Issue by mattpass** [BTCP-community/bitcoinprivate-prefork-website#144]
The websites' home page could really do with some updating, especially removing the snapshot & fork info at the top now we're well past that.

**Comment by mattpass** [comment]
Many of the community want to see an animated roadmap in it's place.

**Comment by mattpass** [comment]
An enhanced idea on the above could be a homepage hero = Responsive slider (auto):
- Slide1 : Splash explaining btcp (CTA to about and FAQ pages)
- Slide 2 : Roadmap (CTA to roadmap duuuuh)
- Slide 3 : Payments Platform (either CTA to internal page exlpaining, or link out to site)

**Comment by daniel-farina** [comment]
New website up soon.
