### ISSUE TITLE
Add 'Feedback' to footer links

### ISSUE THREAD

**Issue by mattpass** [BTCP-community/bitcoinprivate-prefork-website#145]
We now have btcprivate.org/feedback URL which currently shows an Airtable form allowing users to add their feedback - good or bad, for review. It's a constructive place for users to add their ideas, thoughts and opinions.

However, it's not a nav option at all and needs to be added in the footer links, next to 'Privacy'.

**Comment by daniel-farina** [comment]
I'll implement this on the new website @mattpass. Sorry for the late reply. Closing for now.

**Comment by mattpass** [comment]
@daniel-farina No probs - means we can direct people to this if they have an issue rather than try and handle it in Teleggram etc. Much better :-)
