### ISSUE TITLE
Add Medium Blogs on website

### ISSUE THREAD

**Issue by ttran4040** [BTCP-community/bitcoinprivate-prefork-website#21]
Need ability to show our medium blogs on website for SEO purposes.

**Comment by drekli** [comment]
After a quick look last night, there are a range of ways of pulling posts as json:

https://medium.com/@zclassic?format=json

https://medium.com/@zclassic/latest?format=json

Just need a nice method to template and style it.

**Comment by Fj00** [comment]
feature/blog branch

Currently set up for local testing only.
Using posts.json for sample data from another medium site, which does not need to be in production.
In Blog.js, for production, lines 2, 6, 7 will need to be uncommented, and lines 4, 8 will need to be commented out.

**Comment by daniel-farina** [comment]
done.
