### ISSUE TITLE
Add Metatags

### ISSUE THREAD

**Issue by ttran4040** [BTCP-community/bitcoinprivate-prefork-website#25]
<meta name="twitter:site" content="@bitcoinprivate">
<meta property="og:title" content="Bitcoin Private">
<meta property="og:description" content="Bitcoin Private is a hard fork of Bitcoin combined with the privacy of zk-snarks.">
<meta property="og:image" content="images/thumbnail.png">
<meta property="og:url" content="https://btcprivate.org/">

<meta name="twitter:title" content="Bitcoin Private">
<meta name="twitter:description" content="Bitcoin Private is a hard fork of Bitcoin combined with the privacy of zk-snarks.">
<meta name="twitter:image" content="images/thumbnail.png">
<meta name="twitter:card" content="summary_large_image">

**Comment by mattpass** [comment]
Covered in: https://github.com/BTCP-community/bitcoinprivate-prefork-website/commit/320da89bad2e8d63b9f607e1974b70d5fbabe4cc
