### ISSUE TITLE
FAQ - Bittrex addition

### ISSUE THREAD

**Issue by Light-Shinchoku** [BTCP-community/bitcoinprivate-prefork-website#47]
Include news that bittrex will credit BTCP to ZCL holders during their snapshot. "Bittrex will offer Zclassic holders on Bittrex partial support through claiming and withdrawing BTCP." 

https://support.bittrex.com/hc/en-us/articles/360001271272-Statement-on-Zclassic-ZCL-and-Bitcoin-Private-BTCP-

**Comment by mattpass** [comment]
This could be part of the Snapshot Info page I mentioned in #48 I think?
