### ISSUE TITLE
Include "How to Claim BTCP" button somewhere on home page?

### ISSUE THREAD

**Issue by Light-Shinchoku** [BTCP-community/bitcoinprivate-prefork-website#48]
I have been answering calls in support today & lots of people ask this question and don't necessarily know to find it in the 'support' section. Just a thought but we could put a tab on the top like "how to claim BTCP" or something like this.

**Comment by mattpass** [comment]
This sounds like a good idea IMO. Could add a dedicated 'Snapshot' link in the nav and page on the site plus the big 'How to claim BTCP' button just under snapshot block info on Home page which links to it also?

**Comment by Light-Shinchoku** [comment]
Yes, I believe this would help a lot of people out in the next coming days.
