### ISSUE TITLE
Press Contact

### ISSUE THREAD

**Issue by ttran4040** [BTCP-community/bitcoinprivate-prefork-website#49]
- For any press inquiries, please reach out to press@btcprivate.org
- For all official statements, please refer to our Github: and our Twitter / Reddit:

-Bottom of website instead of saying contact us @bitcoinprivate, replace it with press@btcprivate.org

**Comment by mattpass** [comment]
Fixed by https://github.com/BTCP-community/bitcoinprivate-prefork-website/commit/a091d77fc591614e62cc149920dfad8b1d8b08dc
