### ISSUE TITLE
Admin Area, CMS and Page Manager

### ISSUE THREAD

**Issue by mattpass** [BTCP-community/bitcoinprivate-prefork-website#64]
Once the site has a DB available and some improved hosting, we can make use of it and the server side languages that are available.

This will allow us to create an admin area and once logged in, the BTCP team member could add/edit/remove pages as well as add content to those pages (incl text and images, plus links to files such as PDFs).

This would allow any responsible team member to expand the size of the website with new pages and maintain content on those pages easily.

**Comment by daniel-farina** [comment]
new site will address this.
